import type { MenuCategory, MenuItem, TableArea } from "@/lib/types";

export const developerCode = "PARK-88-DEV";

export const tableAreas: Record<TableArea, { label: string; tables: string[] }> = {
  indoor: { label: "실내", tables: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15"] },
  middle: { label: "미들", tables: ["17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"] },
  yard: { label: "야장", tables: ["31", "33", "35", "37", "38", "39", "40", "41", "42", "43", "44", "46", "48"] },
  custom: { label: "기타", tables: [] },
};

export const menuCategoryLabels: Record<MenuCategory, string> = {
  main: "안주",
  fried: "튀김",
  meal: "식사/사리",
  side: "간편",
  drink: "음료",
  alcohol: "주류",
};

export const initialMenuItems: MenuItem[] = [
  { id: "m-한우곱도리탕", category: "main", name: "한우 곱도리탕", price: 25000 },
  { id: "m-대전닭한마리칼국수", category: "main", name: "88 대전 닭한마리 칼국수", price: 23000 },
  { id: "m-춘천순살닭도리탕", category: "main", name: "춘천 순살 닭도리탕", price: 23000 },
  { id: "m-엄성부대찌개", category: "main", name: "엄성부대찌개", price: 22000 },
  { id: "m-도끼스치즈떡볶이", category: "main", name: "도끼스 치즈 떡볶이", price: 21000 },
  { id: "m-부산어묵탕", category: "main", name: "부산어묵탕", price: 22000 },
  { id: "m-88백골뱅이", category: "main", name: "88 백골뱅이+육수", price: 22000 },
  { id: "m-곱창전골", category: "main", name: "곱창전골", price: 22000 },
  { id: "m-물닭구이", category: "main", name: "물닭구이", price: 24000 },
  { id: "m-88매콤치즈쭈꾸미볶음", category: "main", name: "88 매콤 치즈 쭈꾸미볶음", price: 23000 },
  { id: "m-순살간장찜닭", category: "main", name: "순살 간장찜닭", price: 22000 },
  { id: "m-88간장보쌈", category: "main", name: "88 간장보쌈", price: 22000 },
  { id: "m-족뱅이", category: "main", name: "족뱅이", price: 22000 },
  { id: "m-물뱅이", category: "main", name: "물뱅이", price: 22000 },
  { id: "m-88화산콩불", category: "main", name: "88 화산콩불", price: 21000 },
  { id: "m-마라떡볶이납작만두", category: "main", name: "마라떡볶이와 납작만두", price: 19000 },
  { id: "m-독도백짬뽕탕", category: "main", name: "독도 백짬뽕탕", price: 22000 },
  { id: "m-울릉도얼큰짬뽕탕", category: "main", name: "울릉도 얼큰짬뽕탕", price: 22000 },
  { id: "m-의정부부대찌개", category: "main", name: "의정부 부대찌개", price: 22000 },
  { id: "m-부산수제오뎅탕", category: "main", name: "부산 수제오뎅탕", price: 22000 },
  { id: "m-88순살족발", category: "main", name: "88 순살족발", price: 21000 },
  { id: "m-돈가스만난치즈떡볶이", category: "main", name: "돈가스 만난 치즈떡볶이", price: 21000 },
  { id: "m-삼겹과두부김치", category: "main", name: "삼겹과 두부김치", price: 21000 },
  { id: "m-오징어숙회", category: "main", name: "오징어숙회", price: 21000 },
  { id: "m-매운국물닭발주먹밥", category: "main", name: "매운국물닭발과 주먹밥", price: 21000 },
  { id: "m-매운무뼈닭발주먹밥", category: "main", name: "매운무뼈닭발과 주먹밥", price: 21000 },
  { id: "m-매운오돌뼈주먹밥", category: "main", name: "매운오돌뼈와 주먹밥", price: 20000 },
  { id: "m-스팸과두부김치", category: "main", name: "스팸과 두부김치", price: 20000 },
  { id: "m-골뱅이쫄면만두튀김", category: "main", name: "골뱅이쫄면과 만두튀김", price: 21000 },
  { id: "m-대패삼겹한판", category: "main", name: "대패 삼겹 한판", price: 19000 },
  { id: "m-88간장불고기", category: "main", name: "88 간장불고기", price: 19000 },
  { id: "m-88치즈닭갈비", category: "main", name: "88 치즈닭갈비", price: 18000 },
  { id: "m-88고추장불고기", category: "main", name: "88 고추장불고기", price: 19000 },
  { id: "m-88불닭구이", category: "main", name: "88 불닭구이", price: 21000 },
  { id: "m-88든든한보쌈", category: "main", name: "88 든든한 보쌈", price: 22000 },
  { id: "m-딸기화채", category: "side", name: "딸기화채", price: 12000 },
  { id: "m-김치볶음밥", category: "meal", name: "김치볶음밥", price: 12000 },
  { id: "m-촉촉한짜파게티", category: "meal", name: "촉촉한 짜파게티", price: 10000 },
  { id: "m-해장라면", category: "meal", name: "해장라면", price: 5000 },
  { id: "m-우동", category: "meal", name: "우동", price: 5500 },
  { id: "m-쫄면", category: "meal", name: "쫄면", price: 5000 },
  { id: "m-주먹밥", category: "meal", name: "주먹밥", price: 4000 },
  { id: "m-순살후라이드", category: "fried", name: "순살후라이드", price: 22000 },
  { id: "m-순살양념치킨", category: "fried", name: "순살 양념치킨", price: 22000 },
  { id: "m-순살파닭", category: "fried", name: "순살 파닭", price: 22000 },
  { id: "m-후라이드한마리", category: "fried", name: "후라이드한마리", price: 23000 },
  { id: "m-똥집튀김", category: "fried", name: "똥집튀김", price: 14000 },
  { id: "m-염통꼬치", category: "fried", name: "염통꼬치", price: 11000 },
  { id: "m-버팔로윙", category: "fried", name: "버팔로윙", price: 12000 },
  { id: "m-감자튀김", category: "fried", name: "감자튀김", price: 9000 },
  { id: "m-고구마치즈스틱", category: "fried", name: "고구마치즈스틱", price: 10000 },
  { id: "m-케이준감자튀김", category: "fried", name: "케이준감자튀김", price: 9000 },
  { id: "m-88비빔만두", category: "fried", name: "88 비빔만두", price: 10000 },
  { id: "m-88튀김만두", category: "fried", name: "88 튀김만두", price: 9000 },
  { id: "m-눈꽃치즈볼", category: "fried", name: "눈꽃 치즈볼", price: 7000 },
  { id: "m-치즈볼", category: "fried", name: "치즈볼", price: 7000 },
  { id: "m-피카츄돈까스", category: "fried", name: "피카츄돈까스", price: 10000 },
  { id: "m-치즈스틱과샐러드", category: "fried", name: "치즈스틱과 샐러드", price: 7000 },
  { id: "m-포장마차계란탕", category: "side", name: "포장마차 계란탕", price: 8000 },
  { id: "m-개시원한황도", category: "side", name: "개시원한 황도", price: 9000 },
  { id: "m-설탕토마토", category: "side", name: "설탕토마토", price: 7000 },
  { id: "m-노가리와쥐포", category: "side", name: "노가리와 쥐포", price: 12000 },
  { id: "m-먹태", category: "side", name: "먹태", price: 11000 },
  { id: "m-사우나오징어", category: "side", name: "사우나오징어", price: 11000 },
  { id: "m-파인애플사베트", category: "side", name: "파인애플사베트", price: 9000 },
  { id: "m-요구르트사베트", category: "side", name: "요구르트사베트", price: 9000 },
  { id: "m-콩나물해장국", category: "side", name: "콩나물해장국", price: 8000 },
  { id: "m-복어해장국", category: "side", name: "복어해장국", price: 9000 },
  { id: "m-냉면", category: "meal", name: "냉면", price: 6000 },
  { id: "m-물냉면", category: "meal", name: "물냉면", price: 6000 },
  { id: "m-비빔냉면", category: "meal", name: "비빔냉면", price: 6000 },
  { id: "m-우동사리", category: "meal", name: "우동사리", price: 2000 },
  { id: "m-라면사리", category: "meal", name: "라면사리", price: 2000 },
  { id: "m-쫄면사리", category: "meal", name: "쫄면사리", price: 2000 },
  { id: "m-공기밥", category: "meal", name: "공기밥", price: 1500 },
  { id: "m-볶음밥", category: "meal", name: "볶음밥", price: 3000 },
  { id: "m-진로", category: "alcohol", name: "진로", price: 5500 },
  { id: "m-참이슬", category: "alcohol", name: "참이슬", price: 5500 },
  { id: "m-새로", category: "alcohol", name: "새로", price: 5500 },
  { id: "m-카스", category: "alcohol", name: "카스", price: 5500 },
  { id: "m-테라", category: "alcohol", name: "테라", price: 5500 },
  { id: "m-켈리", category: "alcohol", name: "켈리", price: 5500 },
  { id: "m-린", category: "alcohol", name: "린", price: 5500 },
  { id: "m-청하", category: "alcohol", name: "청하", price: 6500 },
  { id: "m-매화수", category: "alcohol", name: "매화수", price: 6500 },
  { id: "m-심술", category: "alcohol", name: "심술", price: 7000 },
  { id: "m-콜라", category: "drink", name: "콜라", price: 2500 },
  { id: "m-사이다", category: "drink", name: "사이다", price: 2500 },
  { id: "m-환타", category: "drink", name: "환타", price: 2500 },
  { id: "m-제로콜라", category: "drink", name: "제로콜라", price: 3000 },
  { id: "m-파워에이드", category: "drink", name: "파워에이드", price: 2500 },
  { id: "m-밀키스", category: "drink", name: "밀키스", price: 2500 },
];
