import type { MenuCategory, MenuItem, TableArea } from "@/lib/types";

export const developerCode = "PARK-88-DEV";

export const tableAreas: Record<TableArea, { label: string; tables: string[] }> = {
  indoor: { label: "실내", tables: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15"] },
  middle: { label: "미들", tables: ["17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"] },
  yard: { label: "야장", tables: ["31", "33", "35", "37", "38", "39", "40", "41", "42", "43", "44", "46", "48"] },
  custom: { label: "기타", tables: [] },
};

export const menuCategoryLabels: Record<MenuCategory, string> = {
  main: "안주",
  fried: "튀김",
  meal: "식사/사리",
  side: "간편",
  drink: "음료",
  alcohol: "주류",
};

export const initialMenuItems: MenuItem[] = [
  { id: "m-88한우곱도리탕대창", category: "main", name: "88 한우 곱도리탕 (대창)", price: 25000 },
  { id: "m-대전닭한마리칼국수", category: "main", name: "88 대전 닭한마리 칼국수", price: 23000 },
  { id: "m-춘천순살닭도리탕", category: "main", name: "춘천 순살 닭도리탕", price: 23000 },
  { id: "m-독도백짬뽕탕", category: "main", name: "독도 백짬뽕탕", price: 22000 },
  { id: "m-울릉도얼큰짬뽕탕", category: "main", name: "울릉도 얼큰짬뽕탕", price: 22000 },
  { id: "m-의정부부대찌개", category: "main", name: "의정부 부대찌개", price: 22000 },
  { id: "m-부산오뎅탕", category: "main", name: "부산 오뎅탕", price: 22000 },
  { id: "m-푸짐한명란알탕", category: "main", name: "푸짐한 명란 알탕", price: 22000 },
  { id: "m-88바지락칼국수", category: "main", name: "88 바지락 칼국수", price: 20000 },
  { id: "m-모듬과일", category: "main", name: "모듬과일", price: 28000 },
  { id: "m-한뚝배기매운갈비찜", category: "main", name: "한뚝배기 매운 갈비찜", price: 24000 },
  { id: "m-한뚝배기돼지갈비찜", category: "main", name: "한뚝배기 돼지 갈비찜", price: 24000 },
  { id: "m-88매콤치즈쭈꾸미볶음", category: "main", name: "88 매콤 치즈 쭈꾸미볶음", price: 23000 },
  { id: "m-88든든한보쌈", category: "main", name: "88 든든한 보쌈", price: 23000 },
  { id: "m-족뱅이", category: "main", name: "족뱅이(족발+골뱅이+쫄면)", price: 22000 },
  { id: "m-물뱅이", category: "main", name: "물뱅이(족발+냉면+육수)", price: 22000 },
  { id: "m-88물닭구이", category: "main", name: "88 물닭구이(+치즈0.3)", price: 21000 },
  { id: "m-돈까스만난치즈떡볶이", category: "main", name: "돈까스 만난 치즈 떡볶이", price: 21000 },
  { id: "m-삼겹두부김치", category: "main", name: "삼겹&두부김치", price: 21000 },
  { id: "m-88치즈닭갈비", category: "main", name: "88 치즈닭갈비", price: 21000 },
  { id: "m-88고추장불고기", category: "main", name: "88 고추장불고기", price: 20000 },
  { id: "m-88연탄불고기", category: "main", name: "88 연탄불고기", price: 20000 },
  { id: "m-딸기화채", category: "main", name: "딸기화채", price: 20000 },
  { id: "m-88화산콩불", category: "main", name: "88 화산콩불", price: 21000 },
  { id: "m-매운무뼈국물닭발", category: "main", name: "매운 무뼈 국물닭발", price: 21000 },
  { id: "m-골뱅이쫄면만두튀김", category: "main", name: "골뱅이 쫄면&만두튀김", price: 21000 },
  { id: "m-간장닭목살구이", category: "main", name: "간장 닭목살구이", price: 19000 },
  { id: "m-매운무뼈닭발", category: "main", name: "매운 무뼈 닭발", price: 19000 },
  { id: "m-치즈계란말이", category: "main", name: "치즈계란말이", price: 18000 },
  { id: "m-순살파닭", category: "fried", name: "순살 파닭", price: 22000 },
  { id: "m-순살양념치킨", category: "fried", name: "순살 양념치킨", price: 22000 },
  { id: "m-순살후라이드", category: "fried", name: "순살 후라이드", price: 21000 },
  { id: "m-옛날통닭", category: "fried", name: "옛날통닭", price: 14000 },
  { id: "m-바삭모듬튀김", category: "fried", name: "바삭 모듬튀김", price: 14000 },
  { id: "m-스팸계란후라이", category: "side", name: "스팸 계란 후라이", price: 12000 },
  { id: "m-뚝배기김치우동", category: "side", name: "뚝배기 김치우동", price: 12000 },
  { id: "m-영통꼬치구이", category: "side", name: "영통꼬치구이(양념/소금/반반)", price: 11000 },
  { id: "m-88된장술밥", category: "side", name: "88 된장술밥", price: 10000 },
  { id: "m-롱고구마치즈스틱", category: "fried", name: "롱 고구마 치즈스틱", price: 10000 },
  { id: "m-피카츄돈까스", category: "fried", name: "피카츄 돈까스", price: 10000 },
  { id: "m-두장등심돈까스", category: "fried", name: "두장 등심돈까스", price: 10000 },
  { id: "m-파인애플사베트", category: "side", name: "사베트(파인애플/요구르트)", price: 9000 },
  { id: "m-개시원한황도", category: "side", name: "개시원한 황도", price: 9000 },
  { id: "m-케이준감자튀김", category: "fried", name: "케이준 감자튀김", price: 9000 },
  { id: "m-88계란탕", category: "side", name: "88 계란탕", price: 8000 },
  { id: "m-눈꽃치즈볼", category: "fried", name: "눈꽃 치즈볼", price: 7000 },
  { id: "m-프렌치토스트", category: "side", name: "프렌치토스트", price: 7000 },
  { id: "m-88꼬마만두튀김", category: "fried", name: "88 꼬마만두튀김", price: 7000 },
  { id: "m-88물만두", category: "side", name: "88 물만두", price: 6000 },
  { id: "m-햄야채볶음밥", category: "meal", name: "햄야채볶음밥", price: 8000 },
  { id: "m-냉면물비빔", category: "meal", name: "냉면 (물/비빔)", price: 6000 },
  { id: "m-해장라면짜파게티", category: "meal", name: "해장라면, 짜파게티", price: 5000 },
  { id: "m-셀프주먹밥", category: "meal", name: "셀프 주먹밥", price: 4000 },
  { id: "m-치즈추가", category: "meal", name: "치즈추가", price: 3000 },
  { id: "m-사리추가", category: "meal", name: "사리(칼국수/라면/우동/쫄면)", price: 2000 },
  { id: "m-공기밥", category: "meal", name: "공기밥", price: 1500 },
  { id: "m-참이슬", category: "alcohol", name: "참이슬", price: 5500 },
  { id: "m-처음처럼", category: "alcohol", name: "처음처럼", price: 5500 },
  { id: "m-린", category: "alcohol", name: "린", price: 5500 },
  { id: "m-선양", category: "alcohol", name: "선양", price: 5500 },
  { id: "m-진로", category: "alcohol", name: "진로", price: 5500 },
  { id: "m-진로골드", category: "alcohol", name: "진로골드", price: 5500 },
  { id: "m-새로", category: "alcohol", name: "새로", price: 5500 },
  { id: "m-새로살구", category: "alcohol", name: "새로살구", price: 5500 },
  { id: "m-새로다래", category: "alcohol", name: "새로다래", price: 5500 },
  { id: "m-테라맥주", category: "alcohol", name: "테라맥주", price: 5000 },
  { id: "m-테라", category: "alcohol", name: "테라", price: 5500 },
  { id: "m-테라라이트", category: "alcohol", name: "테라라이트", price: 5500 },
  { id: "m-켈리", category: "alcohol", name: "켈리", price: 5500 },
  { id: "m-카스", category: "alcohol", name: "카스", price: 5500 },
  { id: "m-카스제로", category: "alcohol", name: "카스제로", price: 4000 },
  { id: "m-카스레몬제로", category: "alcohol", name: "카스레몬제로", price: 4000 },
  { id: "m-선양오크", category: "alcohol", name: "선양오크", price: 6500 },
  { id: "m-청하", category: "alcohol", name: "청하", price: 6500 },
  { id: "m-매화수", category: "alcohol", name: "매화수", price: 6500 },
  { id: "m-별빛청하", category: "alcohol", name: "별빛청하", price: 7000 },
  { id: "m-로제청하", category: "alcohol", name: "로제청하", price: 7000 },
  { id: "m-심술7도", category: "alcohol", name: "심술 7도", price: 7000 },
  { id: "m-심술12도", category: "alcohol", name: "심술 12도", price: 7000 },
  { id: "m-밀키스", category: "drink", name: "밀키스", price: 2500 },
  { id: "m-갈배", category: "drink", name: "갈배", price: 2500 },
  { id: "m-토닉워터", category: "drink", name: "토닉워터", price: 2500 },
  { id: "m-초코에몽", category: "drink", name: "초코에몽", price: 2500 },
  { id: "m-콜라", category: "drink", name: "콜라", price: 2500 },
  { id: "m-사이다", category: "drink", name: "사이다", price: 2500 },
  { id: "m-환타", category: "drink", name: "환타", price: 2500 },
  { id: "m-파워에이드", category: "drink", name: "파워에이드", price: 2500 },
  { id: "m-제로콜라", category: "drink", name: "제로콜라", price: 3000 },
];
